name: Create and Test AppImage

on:
  push:
    paths:
      - 'repack_appimage.sh'
  pull_request:
    types: [opened]
    paths:
      - 'repack_appimage.sh'
  workflow_dispatch:

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y libgtk-3-0 libnotify4 libnss3 libxss1 libxtst6 xdg-utils libatspi2.0-0 libuuid1 libsecret-1-0 squashfs-tools libfuse2

    - name: Download QQ Software
      run: |
        wget https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.6_240322_x86_64_01.AppImage
        mv QQ_3.2.6_240322_x86_64_01.AppImage QQ.AppImage.old
        wget --no-check-certificate --content-disposition https://github.com/AppImage/AppImageKit/releases/download/13/runtime-x86_64

    - name: Run repack_appimage.sh
      run: |
        chmod +x repack_appimage.sh
        ./repack_appimage.sh

    - name: Check output and directory existence
      run: |
        if ! ./QQ.AppImage --logging-enable | grep -q "[LiteLoader]" || [ ! -d "$HOME/.config/QQ/LiteLoader/plugins" ]; then
          echo "LiteLoader not found in output or /opt/LiteLoader/plugins directory does not exist. Test failed."
          exit 1
        else
          echo "LiteLoader found in output and /opt/LiteLoader/plugins directory exists. Test succeeded."
        fi

